stages:
  - build
  - test

variables:
  KNOWROB_MONGO_HOST: mongo
  KNOWROB_MONGO_PORT: 27017

default:
  image: jeremiasthun/knowrob-playground
  services:
    - name: mongo:4.4.9
      alias: mongo
  before_script:
    - PATH_TO_NEEM=$PWD
    - cd /home/validator/catkin_ws/src/knowrob
    - git pull
    - cd /home/validator/catkin_ws/src/neem_validator
    - git pull
    - catkin build
    - source /source_ros.sh

check-mongodump:
  stage: build
  script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$DVC_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cd $PATH_TO_NEEM && dvc pull
    - cat settings/gitlab-ci/check-mongodump.yaml
    - roslaunch neem_validator validator.launch path_to_neem:=$PATH_TO_NEEM workflow_file:=settings/gitlab-ci/check-mongodump.yaml

check-external-resources:
  stage: test
  script:
    - cat settings/gitlab-ci/check-external-resources.yaml
    - roslaunch neem_validator validator.launch path_to_neem:=$PATH_TO_NEEM workflow_file:=settings/gitlab-ci/check-external-resources.yaml

mongodb-schema-required:
  stage: test
  script:
    - cat settings/gitlab-ci/mongodb-schema-required.yaml
    - roslaunch neem_validator validator.launch path_to_neem:=$PATH_TO_NEEM workflow_file:=settings/gitlab-ci/mongodb-schema-required.yaml

mongodb-schema-recommended:
  stage: test
  script:
    - cat settings/gitlab-ci/mongodb-schema-recommended.yaml
    - roslaunch neem_validator validator.launch path_to_neem:=$PATH_TO_NEEM workflow_file:=settings/gitlab-ci/mongodb-schema-recommended.yaml
  allow_failure: true

rosprolog-required:
  stage: test
  script:
    - cat settings/gitlab-ci/rosprolog-required.yaml
    - roslaunch neem_validator validator.launch path_to_neem:=$PATH_TO_NEEM workflow_file:=settings/gitlab-ci/rosprolog-required.yaml

owl-consistency:
  stage: test
  script:
    - cat settings/gitlab-ci/owl-consistency.yaml
    - roslaunch neem_validator validator.launch path_to_neem:=$PATH_TO_NEEM workflow_file:=settings/gitlab-ci/owl-consistency.yaml
