default:
  image: jeremiasthun/knowrob-playground

  services:
    - name: mongo:4.4.9
      alias: mongo

variables:
  KNOWROB_MONGO_HOST: mongodb://localhost.mongo
  KNOWROB_MONGO_PORT: 27017

build-job:
  stage: build
  script:
    - git pull
    - export
    - source /source_ros.sh
    - roslaunch neem_validator validator.launch path_to_neem:=blub

test-job1:
  image: jeremiasthun/knowrob-playground
  stage: test
  script:
    - echo "Hi I'm there"

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
