stages:
  - build
  - test

variables:
  KNOWROB_MONGO_HOST: mongo
  KNOWROB_MONGO_PORT: 27017
  NEEM_VALIDATOR: '/home/validator/catkin_ws/src/neem_validator'
  DB_NAME: $RANDOM$RANDOM

default:
  image: jeremiasthun/knowrob-playground
  services:
    - name: mongo:4.4.9
      alias: mongo
  before_script:
    - PATH_TO_NEEM=$PWD
    - cd /home/validator/catkin_ws/src/knowrob
    - git pull
    - cd $NEEM_VALIDATOR
    - git pull
    - catkin build
    - mv settings/knowrob_config.pl settings/knowrob_config_orig.pl
    - sed '/setting(mng_client:db_name/d' settings/knowrob_config_orig.pl > settings/knowrob_config.pl
    - echo "setting(mng_client:db_name, $DB_NAME)." >> settings/knowrob_config.pl
    - source /source_ros.sh

check-mongodump:
  stage: build
  script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - chmod 600 $DVC_KEY
    - ssh-add $DVC_KEY
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cd $PATH_TO_NEEM && dvc pull
    - cd $NEEM_VALIDATOR
    - cat settings/gitlab-ci/check-mongodump.yaml
    - roslaunch neem_validator validator.launch path_to_neem:=$PATH_TO_NEEM workflow_file:=settings/gitlab-ci/check-mongodump.yaml
    - cat logs/validation_results
    - if [[ $(cat logs/errors) == 1 ]]; then exit 1; fi; exit 0

check-external-resources:
  stage: test
  script:
    - cat settings/gitlab-ci/check-external-resources.yaml
    - roslaunch neem_validator validator.launch path_to_neem:=$PATH_TO_NEEM workflow_file:=settings/gitlab-ci/check-external-resources.yaml
    - cat logs/validation_results
    - cat logs/errors
    - if [[ $(cat logs/errors) == 1 ]]; then exit 1; fi; exit 0

mongodb-schema-required:
  stage: test
  script:
    - cat settings/gitlab-ci/mongodb-schema-required.yaml
    - roslaunch neem_validator validator.launch path_to_neem:=$PATH_TO_NEEM workflow_file:=settings/gitlab-ci/mongodb-schema-required.yaml
    - cat logs/validation_results
    - if [[ $(cat logs/errors) == 1 ]]; then exit 1; fi; exit 0

# mongodb-schema-recommended:
#   stage: test
#   script:
#     - cat settings/gitlab-ci/mongodb-schema-recommended.yaml
#     - roslaunch neem_validator validator.launch path_to_neem:=$PATH_TO_NEEM workflow_file:=settings/gitlab-ci/mongodb-schema-recommended.yaml
#     - cat logs/validation_results
#     - if [[ $(cat logs/errors) == 1 ]]; then exit 1; fi; exit 0
#   allow_failure: true

rosprolog-required:
  stage: test
  script:
    - cat settings/gitlab-ci/semantic-actions-required.yaml
    - roslaunch neem_validator validator.launch path_to_neem:=$PATH_TO_NEEM workflow_file:=settings/gitlab-ci/semantic-actions-required.yaml
    - cat logs/validation_results
    - if [[ $(cat logs/errors) == 1 ]]; then exit 1; fi; exit 0

rosprolog-required:
  stage: test
  script:
    - cat settings/gitlab-ci/semantic-other-required.yaml
    - roslaunch neem_validator validator.launch path_to_neem:=$PATH_TO_NEEM workflow_file:=settings/gitlab-ci/semantic-other-required.yaml
    - cat logs/validation_results
    - if [[ $(cat logs/errors) == 1 ]]; then exit 1; fi; exit 0

rosprolog-required:
  stage: test
  script:
    - cat settings/gitlab-ci/semantic-warn.yaml
    - roslaunch neem_validator validator.launch path_to_neem:=$PATH_TO_NEEM workflow_file:=settings/gitlab-ci/semantic-warn.yaml
    - cat logs/validation_results
    - if [[ $(cat logs/errors) == 1 ]]; then exit 1; fi; exit 0
  allow_failure: true


owl-consistency:
  stage: test
  script:
    - cat settings/gitlab-ci/owl-consistency.yaml
    - roslaunch neem_validator validator.launch path_to_neem:=$PATH_TO_NEEM workflow_file:=settings/gitlab-ci/owl-consistency.yaml
    - cat logs/validation_results
    - if [[ $(cat logs/errors) == 1 ]]; then exit 1; fi; exit 0
  allow_failure: true
